### PR TITLE
master

### PR DESCRIPTION
**Pull request by rhoglund**
Sorry made a bad PR before. But the one line which should've been deleted is still causing crashes.

Here is a new fixed PR. The return value from the removed line is not used, and is causing crashes.

### CODE REVIEW

**Comment by morenoh149** [comment]
please link to the previous discussion and explain what is going on.

**Comment by rhoglund** [comment]
Here is the old PR + discussion:

https://github.com/morenoh149/react-native-contacts/pull/530#issuecomment-651159497

A variable declaration (NSError* contactError) which was reused in code was wrongly removed causing compilation error, so the PR was reverted.

In the new PR only the line:

```[contactStore containersMatchingPredicate:[CNContainer predicateForContainersWithIdentifiers: @[contactStore.defaultContainerIdentifier]] error:&contactError];```

is removed, and variable declaration moved to where it's used.

The return value of [contactStore containersMatchingPredicate:] is not used, so the code is redundant. The line causes crashes when contactStore.defaultContainerIdentifier is nil.

We've gotten several crash reports in our app on this line.

**Comment by morenoh149** [comment]
lgtm
