### ISSUE TITLE
Fix compile error caused by #530

### ISSUE THREAD

**Issue by varungupta85** [morenoh149/react-native-contacts#534]
#530 causes compilation errors on Xcode. It is unable to find `contactError` which is removed in #530 that is used later in the code.
 
@rhoglund

**Comment by morenoh149** [comment]
reverted in https://github.com/morenoh149/react-native-contacts/commit/fe05b37c66f4cd23ddc30f3b296def4b4ddd86b7
