### ISSUE TITLE
property 'windowScene' not found on object of type 'UIWindow *'

### ISSUE THREAD

**Issue by grit96** [morenoh149/react-native-contacts#502]
Since updating to 5.1.0 from 5.0.7 I now get the following error in the Xcode build:

```
node_modules/react-native-contacts/ios/RCTContacts/RCTContacts.m:645:106: error: property 'windowScene' not found on object of type 'UIWindow *'
            UIView *statusBar = [[UIView alloc]initWithFrame:[UIApplication sharedApplication].keyWindow.windowScene.statusBarManager.statusBarFrame];
```

**Comment by demedos** [comment]
Same here with xcode 10.2.1; upgrading to the 11.3.1 does solve the problem

**Comment by grit96** [comment]
Is there any way to still support Xcode 10?

**Comment by demedos** [comment]
i don’t know, at the moment i just fixed the version to the 5.0.7 in my package.json

**Comment by BishalftSaikia** [comment]
"windowScene" is available in iOS 13 SDK, just compile with Xcode 11 it will resolve the issue. 
https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow

**Comment by ermarin** [comment]
Any solution in xcode 10? :(
Or in xcode 11 run apps with ios 9?

**Comment by grit96** [comment]
@ermarin I've pinned my version of react-native-contacts to 5.0.7 until I'm able to update my project to Xcode 11.
